### ISSUE TITLE
Wish: Elevation and facing direction is recorded 

### ISSUE THREAD

**Issue by fdiengdoh** [merlos/iOS-Open-GPX-Tracker#102]
The app did record elevation when tracking, but not when I add waypoint. I wish it could do that. I also wish the app could record the direction faced by the phone(N,S,E,W, or any degree), if I add waypoint or while tracking. 

I did see this elevation issue is created sometime in 2017, but thought its a long time so I guess I could start a new one.

**Comment by vincentneo** [comment]
To have elevation logged for waypoint can be easily implemented, but I believe @merlos didn't do so, probably as he didn't see this need of it. 

That said, to record the direction faced by the phone, would be of higher difficulty, as the GPX file standard (file format that the tracks are recorded as), does not natively contain an attribute that represents the faced direction. To do so, the GPX file must be extended.

**Comment by fdiengdoh** [comment]
I primarily use this app to track route when I go for photographing landscape, and then later using Lightroom, I sync the position recorded on my phone with the time the photos are taken, so, I could get both position and elevation. Sometimes, to conserve battery, I simply put a waypoint on a particular location while taking photos with my DSLR, and later I can manually use the information to geo-tag my shots. 

I can understand its easy to add elevation on waypoints too, and may be a bit complicated to add direction faced (its not a need for me as of now). Hope the elevation could be added in future updates.

**Comment by vincentneo** [comment]
I see. I personally use GPX files for the same purpose as well, except that I didn't know that waypoints could be used for the image geotagging purpose. 

I could add elevation support for waypoint actually, and I do it soon. Unless there's a strong, justifiable reason to why waypoints shouldn't have an elevation value, I believe this will happen by the next release.

**Comment by fdiengdoh** [comment]
> I see. I personally use GPX files for the same purpose as well, except that I didn't know that waypoints could be used for the image geotagging purpose.

It can be done only manually. Not auto tagging. If I took many shots in one location, then all the shots can be tagged together. I would open the gpx file for way point and copy the location data manually and paste in Lr.
