### ISSUE TITLE
Import facility

### ISSUE THREAD

**Issue by Jactari** [merlos/iOS-Open-GPX-Tracker#11]
Enhancement . . . After distance display, I see import (.gpx) as a major feature / opportunity. OGT already has export via mail. Mail is a great way to distribute .gpx tracks because it's simple for all involved. I've noticed that clicking onan  attached .gpx file in Apple mail / IOS causes IOS to offer a list of available apps that can read .gpx files. Selecting a reader (such as 'gpx reader' allows a direct import and display of the track. Maybe making OGT just a .gpx reader -- rather than adding a comprehensive import dialogue -- is a way to to get started with this functionality.

**Comment by merlos** [comment]
Some links for future reference:

How do I get my application to show up in the "Open in..." menu on iOS for a specific document type?
https://developer.apple.com/library/ios/qa/qa1587/_index.html

How to properly share / export GPX files on iOS
http://aplus.rs/2014/how-to-properly-share-slash-export-gpx-files-on-ios/

Document Interaction Programming Topics for iOS
https://developer.apple.com/library/ios/documentation/FileManagement/Conceptual/DocumentInteraction_TopicsForIOS/Introduction/Introduction.html#//apple_ref/doc/uid/TP40010409-SW1

UTI identifier for GPX (com.apple.dt.document.gpx)
http://uti.schwa.io/identifier/com.apple.dt.document.gpx
```json
{
"UTTypeConformsTo": ["public.xml"], 
"UTTypeDescription": "GPX File", 
"UTTypeIdentifier": "com.apple.dt.document.gpx", 
"UTTypeTagSpecification": 
     {"public.filename-extension": ["gpx"]
}
}
```

**Comment by merlos** [comment]
Included in this commit https://github.com/merlos/iOS-Open-GPX-Tracker/pull/39/commits/30f1b86b904438c1ef7ea471b95db6254e86304f

In next release it will be supported.
