### ISSUE TITLE
More map sources

### ISSUE THREAD

**Issue by under-score** [merlos/iOS-Open-GPX-Tracker#122]
So far I have a choice between Apple Map Kit, Open Street Map and Carto DB as map sources. On site I would prefer also some satellite view (Esri Aerial or Google Earth). Is there any chance to implement that?

**Comment by vincentneo** [comment]
I believe it will not be possible for Esri ArcGIS, it seems to require a plan to work, though the plan can be free. As for Google Earth, I don't remember any free APIs or even any APIs for that gives the ability to use tiles maps.

It is still possible to have a satellite map view though, that is if you are fine with Apple Map's version. That can be implemented.

**Comment by under-score** [comment]
**https://developers.arcgis.com** gives 1,000,000 free basemap and geocode transactions per month
**https://github.com/google/earthengine-api** gives 25,000 free map views per day
**https://developer.apple.com/documentation/mapkit** Apple has no limits on access to their location search API

**Comment by vincentneo** [comment]
But having an API ≠ having a tile API (Google Earth).

Also,
> Earth Engine may only be used for development, research, or educational purposes
