### ISSUE TITLE
Duplicated data when selecting "Save and restart new"

### ISSUE THREAD

**Issue by merlos** [merlos/iOS-Open-GPX-Tracker#126]
This only affects versions with Recovery file

**How to reproduce**

1. Open the app and start tracking.
2. Once you have some track points, save.
3. Close the app without resetting the session.
4. Open the app again, and when asked for recovering the session select "Save and restart new"

**Result**
The recovery file size is larger and has duplicated tracks.

**Expected behavior**
Recovery file should be same as saved file.

**Comment by vincentneo** [comment]
Indeed. Will think of a solution.
