### ISSUE TITLE
Can't import gpx file from iPhone

### ISSUE THREAD

**Issue by UzumakiAlfredo** [merlos/iOS-Open-GPX-Tracker#129]
I download the gpx file from Safari, then share the file from file manager to the app but I get this line on the console: couldn’t be moved because you don’t have permission to access “Documents”."

and file will not added to app.

**Comment by vincentneo** [comment]
Hi @UzumakiAlfredo,

Happen to see an email pop by about this issue just now, hence the quick reply.

Basically, can I double check that you are running iOS 13? I believe so, as there is an issue that partly has to do with Apple updated apis breaking things, regarding sharing of files. I have briefly researched on this, as seen in #125. Will look at workarounds soon when time permits me to do so.

**Comment by UzumakiAlfredo** [comment]
Hi @vincentneo,
Yes I'm on iOS 13, and I'm trying to find the problem too...

**Comment by vincentneo** [comment]
@UzumakiAlfredo It must be the same thing then.... it works for me sometimes though. Not sure if its a 13.0 only or 13.1 thing also, as I did update to 13.1

**Comment by UzumakiAlfredo** [comment]
@vincentneo, I replaced the presentReceivedFile function on the commit(#125) with current one but that didn't fix the problem, did I missed anything? I don't know how to get that commit in proper way.

**Comment by vincentneo** [comment]
@uzumakialfredo my apologies for causing your misunderstanding. 
The last commit of #125 was for another issue with iOS 13 support which would cause a crash when the Apple Watch file receive message should be displayed.

The issue that you faced remains unsolved, though I observed that it can work intermittently, based of my testing. I am wondering if adding an action extension would be beneficial, currently.

**Comment by UzumakiAlfredo** [comment]
@vincentneo 
I guess the problem is in Appdelegate -> 'open url' function.
I get this error when try to import a gpx file -> 'Error Domain=NSCocoaErrorDomain Code=513 "“A.gpx” couldn’t be moved because you don’t have permission to access “Documents”'
I tried to fix the problem but I couldn't.

**Comment by vincentneo** [comment]
hi @UzumakiAlfredo, sorry for the delay.
Now it looks like a different issue than I initially thought. Indeed the line you were referring seemed to be the cause. 
 
Am able to fully replicate as well.

**Comment by vincentneo** [comment]
@UzumakiAlfredo 

Commit https://github.com/merlos/iOS-Open-GPX-Tracker/commit/af36452c3d6506f14b4a760ddf0dfb13679beb9a should fix the issue. Can you try it out? My testings shows that it works.

Thank you!

**Comment by UzumakiAlfredo** [comment]
Yeeeaaaa! it works like a charm! 
Good Job!
