### ISSUE TITLE
iOS 13 received files not recognised as supported in app

### ISSUE THREAD

**Issue by vincentneo** [merlos/iOS-Open-GPX-Tracker#137]
Tested with AirDrop,

"would like to share a file that requires an app from the App Store." message will pop up.

File extension is `.gpx`

**Comment by stormshaker** [comment]
Tested with the Share Sheet, ‘Copy to GPX-Viewer’. No error, but file not imported.

**Comment by vincentneo** [comment]
@stormshaker 

I believe that the issue that you are referring to, is already fixed, as part of pr #125, issue #129.

The issue that I am referring to in this, is that with AirDrop gpx file transfer, iOS asks me to get an app to support gpx formats, instead of detecting this app's support

**Comment by vincentneo** [comment]
What I observe:
![IMG_C65E5A1C5B2F-1](https://user-images.githubusercontent.com/23420208/68388538-d565d200-019b-11ea-8487-995ab19b064b.jpeg)

**Comment by stormshaker** [comment]
Yes, issue #129 looks like what I’m seeing - not this issue. Cheers.

**Comment by merlos** [comment]
It seems that this was a bug of iOS 13 and that should be fixed in iOS13.1. 
https://forums.developer.apple.com/thread/118932

For more info see PR #137
