### ISSUE TITLE
Default filename option 

### ISSUE THREAD

**Issue by doomi** [merlos/iOS-Open-GPX-Tracker#146]
It would be nice to have an option to customize the default filenames for saving.
Personally I prefer yyyymmdd for better sorting.

**Comment by merlos** [comment]
Sorry mentioned this on a commit by error and was closed automatically.

Thanks @doomi for your comment

For default names I was thinking in using the current location name instead of dates.

**Comment by doomi** [comment]
Best would be freely configurable. In my case, location based name would be useless.

**Comment by vincentneo** [comment]
I think that a customisable default name interface would be good,
one that can let us choose, day month year, other other variables in whatever way.

**Comment by stretch4x4** [comment]
I would also like to add my support for this.
Loving the app and using it more and more, which means sorting the files is becoming trickier, the options to configure prefixes and suffixes etc would be great. I too would prefix with YYYY-MM-DD but I am sure some other options would also be useful
