### ISSUE TITLE
Wish: auto export of tracks to iCloud, Dropbox or email

### ISSUE THREAD

**Issue by MtnBiker** [merlos/iOS-Open-GPX-Tracker#149]
Great if automagically exported track to iCloud or Dropbox or via email. Daily would be nice or as a set-able option when Pausing or Saving.

Sharing is already implemented, so it's close to being available—easy for me to say, I don't know Swift.

Thanks for listening.

**Comment by vincentneo** [comment]
Sorry, but I couldn't quite get what you mean.

Mind if you could share a use-case example of how this would be like ~ and how it helps you use the app?

**Comment by stretch4x4** [comment]
I could use something like this, so will detail my current use case.
Currently I use the app to track where I have taken photos, if I do a walk I turn it on and when finished save it. Sometimes this leads to multiple short tracks a day.
When I want to geolocate my photos once home again, I have to transfer each GPX track manually to onedrive and then download it for use / archive on my PC. I think I still have a few tracks on my phone that I haven't backed up yet as I haven't edited those photos yet and can't remember which files I have transferred and which I haven't yet.
If it automatically put all of the GPX files into a folder on onedrive for me that would certainly reduce a lot of my manual process.

Thanks

**Comment by MtnBiker** [comment]
stretch4x4 spelled out my main use case. I tend to leave a tracker on more for tracking outdoor activities—hiking, biking, back country skiing also. But syncing locations to my photos is the main purpose. I have a script to write to my photos and also change the filename to the local date and time. I missed @vincentneo request but did see stretch4x4 response. Thanks for listening.

**Comment by MtnBiker** [comment]
Thank you
