### ISSUE TITLE
Change waypoint name crashes the app

### ISSUE THREAD

**Issue by merlos** [merlos/iOS-Open-GPX-Tracker#151]
Steps

1. Open GPX Tracker with a new empty session
2. Start Tracking
3. Add a waypoint with long press (or button)
4. Rename the waypoint
5. Save the GPX session data
6. Add a new waypoint with long press (or button)
7. Rename the waypoint

and

1. Open GPX Tracker with a new empty session
2. Add a waypoint with long press (or button)
3. Rename the waypoint
4. Save the GPX session data
5. Add a new waypoint with long press (or button)
6. Rename the waypoint

**Comment by vincentneo** [comment]
I think it has to do with `ViewController` line 1128.

Will try a workaround, possibly in the next few days.
