### ISSUE TITLE
Wish: GPX filename prefix dates should be in ISO format.

### ISSUE THREAD

**Issue by ckeller42** [merlos/iOS-Open-GPX-Tracker#153]
Hi,

with German language settings (on Watch and phone) the dates of the filename a start with the day. This does not sort the files in a meaningful way. Would be better have the files start with YYYY-MM-DD (iso 8601 - https://xkcd.com/1179/ ;-) ).

Thanks

**Comment by vincentneo** [comment]
-Related to #146 

In future, we should have a customisable default filename interface.
