### ISSUE TITLE
Translation into "Suomi"

### ISSUE THREAD

**Issue by Phiilman** [merlos/iOS-Open-GPX-Tracker#163]
br
Phiilman

[suomi_finnish.zip](https://github.com/merlos/iOS-Open-GPX-Tracker/files/4397123/suomi_finnish.zip)

**Comment by vincentneo** [comment]
Hi @Phiilman 

Thanks for your contribution for translating the app into Finnish language! Will do a pull request later in the week, when I access my Mac.

Vincent
