### ISSUE TITLE
Reset button too close to Save button –> leads to accidental map resets

### ISSUE THREAD

**Issue by Wookbert** [merlos/iOS-Open-GPX-Tracker#165]
I just tried this app for the first time, and immediately noticed that there is a major UI/UX flaw: The **reset track** button is right next to the **save track** button (see attached image). So if you want to save the map, you might actually reset the map by accident, is the reset function isn't even asking for confirmation.

I'd strongly suggest to move the reset button away from the save button, somewhere else on the screen. Furthermore it should ask for confirmation when hit („Do you really want to reset tracked path?“).

![D3D72BD7-D4E0-452A-9A19-44A170701184_1_105_c](https://user-images.githubusercontent.com/3104762/79075631-5d747880-7cf4-11ea-9e9e-3c760defac00.jpeg)

**Comment by merlos** [comment]
@Wookbert Yep, I fully, agree, it is something that has been missing since the beginning of times. Ad minimum, the clear button should have a confirmation or an undo action.

Regarding changing the location... for now, as a quick fix I´ll will increase the distance between buttons to minimize the mistake press. I kinda like the symmetry bar, but I agree on the 'danger' of having both buttons close.

Thanks for your comment. Juan.

**Comment by Wookbert** [comment]
An alternative quick fix could be to require a long press to trigger delete. No idea how intuitive that would be.

**Comment by Wookbert** [comment]
This would be the „safest“ (= mishap proof) design IMO. There's also a design inconsistence with the blue icons in the top left corner: Why does the folder icon have a white circular backdrop, but the other blue icons not!?

Speaking of this: One could consider the replace the red delete button in this layout with a blue trash can icon or a blue X in a blue outline circle.

![image](https://user-images.githubusercontent.com/3104762/79614836-ac118080-8101-11ea-9a67-3223b2556e0e.png)

**Comment by vincentneo** [comment]
Hi all,

I always had an reimagined idea of how UI could look like in Open GPX Tracker, here's my concept (done in Adobe XD):

![Screenshot 2020-04-18 at 8 24 37 PM](https://user-images.githubusercontent.com/23420208/79637619-8e9cef00-81b3-11ea-81bf-91ff8f3ab581.jpg)

A draggable interface is used, for two reasons:
- New users will be able to understand it better: native Maps app use it.
- Serves as reset trigger. Impossible to mis-trigger, as the drag function is used solely for resetting the season.

Share button have been moved down, as I am representing the whole drag UI as a session by itself. Anything exclusive of the current session should be in the drag UI. This is why the speed/distance travelled/time elapsed are all relocated there.

This concept, should also solve earlier concerns like #97.

What do you all think? Do give me some feedback!

Vincent.

**Comment by Wookbert** [comment]
The color scheme is too chaotic (sorry, for that), too vivid, but other than that, it clearly goes into the right direction.

Alternative for clearing the map: Instead of rubber band pulling further up, swipe trash can to the left.

**Comment by Wookbert** [comment]
The icon language also should be unified. Currently some icons are blue outlined with or without infill (folder icon has infill), some with white backdrop, some without, some icons are bold, some are fine, some are black, some are full color.

I'm missing consistency here. Should be much more subtle.

**Comment by Wookbert** [comment]
One should also left align all top left items (incl. "Open GPX Tracker") with the bottom left items, and right align all top right items with all bottom right items. Think of an overall clean block.

**Comment by vincentneo** [comment]
@Wookbert I fully agree with you on my color scheme, actually. Quick mockup and I just focused on randomly assigning similar colours. 

The icons back when some were redesigned, was quite closely aligned with what it looks like back then, just slightly modernised. I didn't bother touching them at all right now in the mockup so yeah. Would work on it, but not yet. The trash can to the left though, can you elaborate? 

For the top alignments, do you mean the text on the left to be alighted on the same left margin, or with left margin and of same width? (like equally space icons apart), and same width on the right? Like this:

![Screenshot 2020-04-18 at 9 29 27 PM copy](https://user-images.githubusercontent.com/23420208/79639071-c7d95d00-81bb-11ea-950d-948712a6b833.jpg)
(pardon the loss of the iPhone X notch)

P.S: Looking at the screenshot above, I should align both left and right to be of the same height. The misalignment is obvious... 

Thanks for your advice overall!

**Comment by merlos** [comment]
Thank you both for your comments. Please, to keep things ordered, stick to the topic of the issue.

I have opened **#166** for discussing changes of design, a new design would come in a 2.0 version that would also require a complete overhaul of the code also to make it more modular and reusable. Feel free to continue this interesting discussion over there.

As I said, for now, the solution to this issue will be the confirmation and separate the buttons.

Thanks, Juan.

**Comment by drakkhen** [comment]
+1 Looking forward to the confirmation prompt!  Thanks!

**Comment by swifty99** [comment]
+1 for the prompt. Had a fat finger and lost a good track. 

Fantastic project anyway.

**Comment by Wookbert** [comment]
The current iOS version of Open GPX (v1.7.2, no updates since January 2020?) still lacks this reset confirmation. When will the next version be released?
