### ISSUE TITLE
Satellite Map

### ISSUE THREAD

**Issue by davequ** [merlos/iOS-Open-GPX-Tracker#167]
Is there any way to provide a satellite map? 
This is exactly the program we would like to use for our charity (www.elcv/org/uk) where we are plotting invasive plants. These are normally in featureless countryside, so a satellite view would be a great help.

**Comment by vincentneo** [comment]
Should the Apple Maps's satellite mode suffice, it is implementable.

Though, I would be busy for the coming week... Hence I might not be able to respond quickly.

**Comment by davequ** [comment]
That would be great! Even better if it would cache the area whilst in wifi to avoid using data when out. There is no urgency - its not a necessity, but would be a help.

**Comment by vincentneo** [comment]
Hi @davequ,

I've added satellite map in https://github.com/merlos/iOS-Open-GPX-Tracker/commit/b9c87486b7f2a4b918692d565e28d0b025ef53e7. Though, from a UI perspective, I am not quite pleased with it, as the black text is hardly visible under the satellite map, while white doesn't seem to make it better either. I would probably come back to this eventually though.

**Comment by davequ** [comment]
Wow I am impressed with your speed. That's what happens when one deals with
a one man band instead of a large organisation! Can I download from github
or do I need to wait until you upload to app store?

**Comment by vincentneo** [comment]
Hi @davequ,

Actually this project is maintained by two person, @merlos and I.
To try out right now, you can compile the modified version yourself and side load it on your device, using Xcode by compiling the code.
