### ISSUE TITLE
Enable file sharing through iTunes

### ISSUE THREAD

**Issue by daviewales** [merlos/iOS-Open-GPX-Tracker#17]
iTunes file sharing would allow people to copy all GPX traces to a computer without needing to email them one by one.

Have a look at the image below for an example of what iTunes file sharing looks like.

![iTunes file sharing](https://cloud.githubusercontent.com/assets/2499066/11012831/cbd78fe4-854e-11e5-9354-f6c4991b97f3.png)

**Comment by MtnBiker** [comment]
This would be great.

I'd like to see an additional enhancement which would be to automatically mail or send to a server a daily track every day at midnight (could be some other time, maybe 0 GMT. Would have to account for situations where the phone is off, etc. The basic request is a regular posting of the track. One of my uses is to geocode photos for which I currently use a dedicated GPS device.

**Comment by merlos** [comment]
Hi @daviewales 
It has just been included on the master branch thanks to a pull request of @raphaelschaad 

@MtnBiker I guess syncing the folder of the app with dropbox or something like that could make it... but I have to see the feasibility.

Best, Juan.

**Comment by MtnBiker** [comment]
> On Aug 28, 2016, at 12:19 PM, Merlos <notifications@github.com> wrote:
> 
> Hi @daviewales <https://github.com/daviewales> 
> It has just been included on the master branch thanks to a pull request of @raphaelschaad <https://github.com/raphaelschaad>
> @MtnBiker <https://github.com/MtnBiker> I guess syncing the folder of the app with dropbox or something like that could make it... but I have to see the feasibility.
> 
> Best, Juan.
> 
Yes, Dropbox would do it. In fact that’s where I currently keep my gpx files.

Thanks for considering my request

Greg
