### ISSUE TITLE
Auto lock setting

### ISSUE THREAD

**Issue by doedje** [merlos/iOS-Open-GPX-Tracker#18]
I noticed the track recording turns off during auto-lock... Which could be solved with disabling the auto-lock (by setting) or continue to record gps tracking while in auto-lock. I'd prefer the latter but I am not sure whether that is an option....

(I am working on a gps app myself in swift2, so your project has me interested in many ways!!! Keep it up)

**Comment by doedje** [comment]
OTR: I am planning to make my apps source code thru github too.... And I will fork yours.... And star it and stuff

**Comment by dchang0** [comment]
If you mean that during the iPhone's screen auto-lock, Open GPX Tracker stops tracking, I am experiencing exactly the same problem with v1.1. This is on an iPhone 5S running the app downloaded directly from the App Store (not built from source).

**Comment by Jactari** [comment]
Are you guys planning to add caching to the app?

**Comment by doedje** [comment]
@Jactari: is your question related to the feature request to have a 'disable auto-lock' setting as I propose in this issue in any way? If not please consider opening another issue...

**Comment by doedje** [comment]
@Jactari: I misinterpreted your question I guess.... Sorry about that. I do now understand your question _is_ related to our discussion here... =]
The matter is that when the phone goes into auto-lock (after 1 minute on my pretty fresh out-of-the-box iPhone6S+ so I guess it to be the default) it 'LOOKS' like it stops tracking.... (will have a look if it is really the case) and continues tracking after unlocking the phone.
I see two options to fix this:
- the easiest would be to add a 'disable auto-lock' setting
- somehow continue tracking during auto-lock, what you refered to as 'caching' I guess...

I tried the app on the simulator and noticed it DOES continue tracking when I hit the 'LOCK' feature from the Simulator App's menu. Don't know how to have it go into auto-lock tho...

(again my humble apologies for the somewhat irritated tone in my previous post....)

**Comment by doedje** [comment]
I added `idleTimerDisabled = true` to the appDelegate main application function, which seems to work for me with both GPX Tracker and my own application. Making it available as a setting shouldn't be to hard. I am just not that experienced with iOS development at the moment, but will get back at it when I advanced that far!

```
  func application(application: UIApplication, didFinishLaunchingWithOptions launchOptions: [NSObject: AnyObject]?) -> Bool {
      // Override point for customization after application launch.
      UIApplication.sharedApplication().idleTimerDisabled = true
      return true
  }
```
