### ISSUE TITLE
Translation into Dutch

### ISSUE THREAD

**Issue by julian08100** [merlos/iOS-Open-GPX-Tracker#181]
Idk if I'll maintain it, you can send it and I might translate it.
[InfoPlist.strings.txt](https://github.com/merlos/iOS-Open-GPX-Tracker/files/5058242/InfoPlist.strings.txt)
[Interface.strings.txt](https://github.com/merlos/iOS-Open-GPX-Tracker/files/5058243/Interface.strings.txt)
[Localizable.strings.txt](https://github.com/merlos/iOS-Open-GPX-Tracker/files/5058244/Localizable.strings.txt)

**Comment by vincentneo** [comment]
Hi @julian08100,

Personally am quite busy with life, apologies with the late response. 
Thank you for your translations, and I will try and add these in, when I become more free. 

Vincent

**Comment by vincentneo** [comment]
Hi @julian08100,

The translation `"START_TRACKING" = "Beginnen met traceren";`, appears to be too long.
Is it possible to have a shorter translation?

<img width="417" alt="Screenshot 2020-08-28 at 11 23 23 PM" src="https://user-images.githubusercontent.com/23420208/91584688-981a3d00-e985-11ea-9b5a-5974e788b9ae.png">

**Comment by julian08100** [comment]
You can use “Starten”.

**Comment by vincentneo** [comment]
Ok
