### ISSUE TITLE
Feature request: Add OpenSeaMap information

### ISSUE THREAD

**Issue by eriwst** [merlos/iOS-Open-GPX-Tracker#187]
It would be a nice extension if your app could show nautical information from openseamap.

**Comment by vincentneo** [comment]
Hi, I tried getting tile data from https://tiles.openseamap.org/seamark/{z}/{x}/{y}.png, don't think it works.

**Comment by merlos** [comment]
<img width="300" alt="Screenshot 2023-05-28 at 4 18 40 AM" src="https://github.com/merlos/iOS-Open-GPX-Tracker/assets/404446/f530fb65-3292-4c1b-bc82-56d5ea71571b">
