### ISSUE TITLE
Hi, could you please help me with this issue; when i try to run, it show me this error: import UiKit  - cannot load module UIKit 

### ISSUE THREAD

**Issue by dafal200077** [merlos/iOS-Open-GPX-Tracker#2]

**Comment by merlos** [comment]
Hi! I believe you opened the .xcodeproj. Try opening OpenGpxTracker.xcworkspace

**Comment by Jactari** [comment]
Opening the code in .xcworkspace – as Juan suggested – allowed a successful build. However, Xcode flagged some issues, for which a screen grab which is attached.
![screen shot 2015-10-25 at 09 00 36](https://cloud.githubusercontent.com/assets/14841380/10714815/110423dc-7af7-11e5-98a4-cb206e67d423.png)
This was run for IOS9 iPad retina display and the simulator ran this fine on my iMac. The latest GUI (with distance view and map tile server options etc) was displayed and the functions worked fine. Xcode, at the same time, successfully loaded and launched the app on the iPad BUT the app loaded was the old version. The original OGT app had been deleted prior to this.
