### ISSUE TITLE
Open other maps; import GPX data?

### ISSUE THREAD

**Issue by NamedArray** [merlos/iOS-Open-GPX-Tracker#200]
Can I use a map that I downloaded from the USGS (like a hiking trail for a National Park)?  OR, is the idea that OpenStreetMap will already have a lot of the USGS "hiking trail" data?

Can I import a GPX file, and then view my current location on top of the imported route?

**Comment by merlos** [comment]
USGS as data source is not currently supported. In my experience open street maps has good maps of the national parks tails. To have the maps offline prior to your trip you have to browse the area in the app at different zoom levels.

You can import a GPX file with a route and see your current location at the same time. What is not supported is to track your session as an independent one when you have a file loaded. If you track your position it will be appended to the GPX file you had already loaded. 

Best.
