### ISSUE TITLE
App occasionally crashes on entering files table view 

### ISSUE THREAD

**Issue by vincentneo** [merlos/iOS-Open-GPX-Tracker#203]
Happens randomly, final console message appears unrelated:
```
2021-05-10 23:42:56.615191+0800 OpenGpxTracker[624:80748] [Snapshotting] Snapshotting a view (0x103a83600, UIKeyboardImpl) that is not in a visible window requires afterScreenUpdates:YES.
```

EXC_BAD_ACCESS at com.Metal.CompletionQueueDispatch queue

<img width="613" alt="Screen Shot 2021-05-10 at 11 45 30 PM" src="https://user-images.githubusercontent.com/23420208/117686824-d0973980-b1e9-11eb-9ece-c83bb82d3b46.png">

Unsure why AVAudioSession is shown here though.

Tested Xcode 12.5 / iOS 14.5.1

**Comment by sanketgarade** [comment]
Crashes on my device every time, as a result I'm unable to access the files at all. Below is a screen recording. 

App version 1.9.0 on iPhone mini 12 running iOS 16.5. 

https://github.com/merlos/iOS-Open-GPX-Tracker/assets/74632379/25a1876e-2bd5-45f3-8331-2d9bc16a7e2c

**Comment by merlos** [comment]
Related with #271
