### ISSUE TITLE
Change filename pattern to "%Y-%m-%d-%H%M"

### ISSUE THREAD

**Issue by csware** [merlos/iOS-Open-GPX-Tracker#209]
I'd propose a change for the default filename pattern to "%Y-%m-%d-%H%M" (e.g., "2021-07-09-1528") as this allows to sort the .GPX files more easily (just by filename).

Thanks for this app!

**Comment by geezerhiker** [comment]
Why not use the ISO8601 format? iOS supports it.

**Comment by vincentneo** [comment]
The main branch version has a configurable filename format actually. Eventually when it gets released on the App Store, you should be able to set that in the Settings.

**Comment by chrisspiegl** [comment]
Will there be a release to app store at some point? I had a test release build but that expired and I am wondering hopefully 🌸.
