### ISSUE TITLE
Mapquest Open Street Map tiles

### ISSUE THREAD

**Issue by om-henners** [merlos/iOS-Open-GPX-Tracker#23]
Hi,

As of 11 July this year MapQuest aren't providing their OpenStreetMap tiles without an API key (see https://lists.openstreetmap.org/pipermail/talk/2016-June/076106.html) - this means the tiles in the app are coming through with the message from MapQuest for the API key.

**Comment by merlos** [comment]
Thanks @om-henners for pointing it out. 

There is a new commit that removes MapQuest maps.

In a few days I should be publishing a new version (1.2) of the app in the AppStore without that tile server.

**Comment by om-henners** [comment]
Nice one. Thanks @merlos !
