### ISSUE TITLE
Wish: additional warning when cancelling recovery

### ISSUE THREAD

**Issue by achisto** [merlos/iOS-Open-GPX-Tracker#241]
Today I had to restart my phone because of a bug unrelated to GPX tracker. Therefore, GPX-tracker offered me to recover my track when opening it again after the restart. I mis-clicked on "Cancel" instead of "Save and start new" which led to 9 hours of tracking data being completely lost. There should be an additional pop-up "are you sure you want to cancel and irrevocably delete the so-far tracked route" and only after one has confirmed that as well the data should be erased.

**Comment by merlos** [comment]
Replaced request by #245
