### ISSUE TITLE
Import GPX Tracks

### ISSUE THREAD

**Issue by BigV57** [merlos/iOS-Open-GPX-Tracker#251]
Great app. Would be great to be able to import a gpx from other sources.

**Comment by merlos** [comment]
Thanks :)

Can you please elaborate? 

Currently, as long as you can send the file to your phone (for example, via email or to any cloud provider file viewer), you should be able to open it with Open GPX Tracker.

**Comment by BigV57** [comment]
Excellent, that's one option that I did no try. Great effort mate.
