### ISSUE TITLE
Top labels hidden by Dynamic Island on version in App Store

### ISSUE THREAD

**Issue by mtzfederico** [merlos/iOS-Open-GPX-Tracker#252]
The label with the location coordinates is covered by the Dynamic Island on the iPhone 14 Pro. I built the app on my computer using Xcode 14.3.1 and this doesn't happen on that build, only on the one in the App Store (Version 1.8.0).

I didn't modify the App on my machine, could this be caused by the new version of Xcode?  

## Screenshot of App Store Version
![appStore](https://github.com/merlos/iOS-Open-GPX-Tracker/assets/44717422/7721ded4-874a-40e0-abb4-d0381fa6b578)
  
## Screenshot of my build
![myBuild](https://github.com/merlos/iOS-Open-GPX-Tracker/assets/44717422/06826611-2d3d-4e5c-a909-6c2705d81a78)

**Comment by vincentneo** [comment]
If you are building from the master branch, it's fixed because a while ago I created and merged #230, which fixes this issue.

The App Store version does not contain this fix yet.

**Comment by mtzfederico** [comment]
Perfect, sorry about the duplicate report.

Is there any timeline for updating the App Store Version?

**Comment by vincentneo** [comment]
Let's call @merlos into this conversation

**Comment by merlos** [comment]
Hi!
v1.9.0. My aim is to submit it this or next week.
