### ISSUE TITLE
controlling maps by Keyboard Bluetooth

### ISSUE THREAD

**Issue by lubaldi** [merlos/iOS-Open-GPX-Tracker#265]
Hi, 
i develop Bluetooth Keyboard for Motorcycle, it can manage the navigation app by button for operation like:
Zoom In
Zoom Out
Pan
Center map
rotate map

is possible manage [Open-GPX-Tracker] bye external Keyboard?

**Comment by merlos** [comment]
Hi, 

Nop, there is no support to external keyboards.
