### ISSUE TITLE
Background tracking

### ISSUE THREAD

**Issue by jrmgx** [merlos/iOS-Open-GPX-Tracker#266]
I was wondering if the app continues to track if the iPhone screen is off, or even if another app is in foreground? 
I did not see any mention of that feature on the website/app store page.
It would be a nice improvement, and if it is not possible yet, I'm willing to try to implement it (if it makes sense for the project).

Does the feature exist?
Are you interested to have it?

I'm not a iOS developer anymore, but I can try :)

**Comment by vincentneo** [comment]
This should currently be the case if the user sets the location permission to "Always"

That said, iOS has the final say when it comes to whether if the app will be kept active in the background or not.

**Comment by jrmgx** [comment]
I'm not perfectly sure, as my iOS dev skill are quite rusty, I think I remember that it exists some *background permission* to have the app continuing to work in any case?
Or some kind of wake-up mechanism with a schedule?

Anyway, I'm not asking you to implement it, I may take some time to try myself :)

**Comment by merlos** [comment]
I'm closing this issue. This feature is already working. A few days back I forgot to stop the tracking and continued using the phone normally, a some hours later I realized I had it on all the time.

Something that has changed is that the first time the location is requested,  by default iOS only provides the option of one time or while the app is working/being used" or something like that. However, if the app remains in background, eventually the OS asks if you want it to always allow tracking your position.
