### ISSUE TITLE
Resume tracking issue

### ISSUE THREAD

**Issue by fdiengdoh** [merlos/iOS-Open-GPX-Tracker#29]
I think its a bug or is it just in my phone. I'm using iPhone 5 with latest iOS 9 and whenever I pause tracking and tap on resume it didnot continue to track. I have to close the app and start tracking fresh.

**Comment by merlos** [comment]
@fdiengdoh iOS 9.3.5?

**Comment by fdiengdoh** [comment]
not only 9.3.5 earlier too, at first I thought I made some mistakes but after it occurs many times so I thought it might be a bug.

**Comment by merlos** [comment]
Thanks @fdiengdoh 

Could you please tell me if the steps to reproduce the crash are something like:

1) Open the app
2) Press Start tracking
3) Wait 1 min and press Pause
4) Press Resume <app does not respond>

I'm wondering if it may be something related with memory...
Thanks, Juan.

**Comment by fdiengdoh** [comment]
I forget to mention the steps. 
It happens after long trek like half hr I stop to rest so paused then when I resume it don't resume had to quit the app and then re-track.

With few minutes it resumed

**Comment by merlos** [comment]
Thanks. That will help me.

**Comment by nxet** [comment]
I have been experiencing this as well on iOS11. The trace can be 10m or 20km long, if I pause tracking on resume the line won’t be drawn anymore.
I have no means to tell if the location is still being saved or help otherwise, because I can’t export any of the traces I saved (another issue opened just now).

**Comment by merlos** [comment]
This should be solved with the fixes done in #41. 

Now the app is a bit more clever and reminds the OS to send it the location updates when it comes back from background.
