### ISSUE TITLE
Swift 1.2 compatibitlity

### ISSUE THREAD

**Issue by magge73** [merlos/iOS-Open-GPX-Tracker#3]
I tried to convert the source to swift 1.2 and replaced "UiKit" with "UIKit" but I still get several compiler errors like this one:

/Users/testprojects/iOS-Open-GPX-Tracker-master/OpenGpxTracker/GPXWaypoint+MKAnnotation.swift:66:17: Method 'setCoordinate' with Objective-C selector 'setCoordinate:' conflicts with setter for 'coordinate' with the same Objective-C selector

**Comment by merlos** [comment]
Hi magge73,

I'm still using a previous version of swift, but maybe this can help you:
http://stackoverflow.com/questions/29457720/compiler-error-method-with-objective-c-selector-conflicts-with-previous-declara

Regards, Juan

**Comment by merlos** [comment]
Last commit (https://github.com/merlos/iOS-Open-GPX-Tracker/tree/11e1eda3056c2cc9c3f2b04159cf04f4f37357a8) is already supporting swift 2.0 and XCode 7.0
