### ISSUE TITLE
track (line) not saved on gpx file when there is a long distance and waypoints

### ISSUE THREAD

**Issue by PHubaut** [merlos/iOS-Open-GPX-Tracker#31]
I may have completely missed the purpose of the App and/or missed to activate some feature.
I expected from a "tracker" to be able to hike or ride and get the track 25km ride marked 3 "manual waypoints" on the way and after the ride saved data to a GPX file.
The GPX file contained the 3 manual waypoints but nothing regarding the track.
Again, this may simply be a misuse of the App and if so apologise for this post.
Regards, Pierre
[Tousr a vélo 2016-09-24.gpx.txt](https://github.com/merlos/iOS-Open-GPX-Tracker/files/491572/Tousr.a.velo.2016-09-24.gpx.txt)

**Comment by merlos** [comment]
Hi Pierre,

Thanks for your report and sorry for the delay in the answer. 

Another user reported the problem. 

It seems it is related either with long distance/long time tracks or less probably with tracks in which are added waypoints. 

Thanks, Juan.

**Comment by merlos** [comment]
I think this should be related and fixed at the same time of #41.

Please feel free to open it again if it continues in next release.

Thanks for reporting.
Juan.
