### ISSUE TITLE
No Routes When Starting With A WayPoint - IPhone5

### ISSUE THREAD

**Issue by caseytronic** [merlos/iOS-Open-GPX-Tracker#33]
Routes do not display and record to a file when I add a waypoint before pressing the Start Tracking button.  this only happens if my first action on loading the app is to set a waypoint.  If I open the app and start tracking a route first, both routes and waypoints function normally.  Also, if I reset the route ( after recording a route before any waypoints), and then add a waypoint first, both routes and waypoints function normally.

This was observed on an IPhone 5 with the latest version of the app.  The issue persisted after removal and reinstallation of the app.

**Comment by merlos** [comment]
This issue is related with #41. 

This issue was solved the changes defined on that thread.
