### ISSUE TITLE
Not possible to see the description of waypoints in a gpx file.

### ISSUE THREAD

**Issue by sordoneF** [merlos/iOS-Open-GPX-Tracker#34]
I use the app to see EV chargepoint data in offline mode. When I import a gpx file I can only see the <name> CDATA fields. I also want to see the <desc> CDATA fields.
Can you fix this ? I have attached a sample gpx file.
[GoingElectric (4).gpx.zip](https://github.com/merlos/iOS-Open-GPX-Tracker/files/632556/GoingElectric.4.gpx.zip)

If possible (nice to have) can you add a text filter option so I can filter for example on 43kw (faster but less) and 22kw/11kw (slower but more) chargepoints with one file ? Or color code (red/orange/yellow) them ?

**Comment by merlos** [comment]
Reviewed this issue in 1.6.1 version.

CDATA fields are displayed with its contents.
