### ISSUE TITLE
Just a Thought

### ISSUE THREAD

**Issue by fdiengdoh** [merlos/iOS-Open-GPX-Tracker#35]
Been using your Open GPX tracker for iOS for a while. But unfortunately I had to shift to Android phone (still using iPad though). Yet as open as Android is supposed to be, I still can't find a replacement of a lightweight GPX tracker like yours. I don't know if this would be the right place to say, but will you take the opportunity to code for Android too.

**Comment by merlos** [comment]
Hi @fdiengdoh!

Thanks for your comment. At this time I do not have plans to port the code to Android... but thanks for the suggestion. Maybe, sometime in the future 💃 

Best, Juan.
