### ISSUE TITLE
Can't send by email when track is big

### ISSUE THREAD

**Issue by hiniesta** [merlos/iOS-Open-GPX-Tracker#36]
When a track is too big, send by email doesn't work. There is no way to recover/export the track

**Comment by merlos** [comment]
Hi @hiniesta,

Thanks for your comment. Which size are you trying to send? 

Alternatively to the email, Open GPX tracker supports iTunes File Sharing. Here you have the instructions:

![open-gpx-tracker-itunes-file-sharing](https://cloud.githubusercontent.com/assets/404446/23881805/2ab3e14c-085d-11e7-9f30-7790458bb28a.png)
