### ISSUE TITLE
No elevation is saved when creating a gpx file with waypoints, only lat/lon

### ISSUE THREAD

**Issue by just-Addict** [merlos/iOS-Open-GPX-Tracker#38]
I was creating a gpx file using waypoints and when I emailed it to be used in a 3D route visualizer project, I discovered the elevation was not added, which rendered the created file useless for the purpose I had envisioned.

**Comment by merlos** [comment]
Hi @just-Addict 
Reviewing the issue, it seems that it may be related with the device you are using. Which one are you using?

This is an excerpt of two GPX files recorded with an iPhone 6S. One of them was recorded during a flight and the other was recorded close to the sea level in **2015**, in an early version of GPX tracker. The elevation was correctly saved in both cases.

```
<trk>
		<trkseg>
			<trkpt lat="9.395658" lon="-81.401710">
				<ele>11535.913086</ele>
				<time>2016-11-06T14:22:47Z</time>
			</trkpt>
			<trkpt lat="9.394165" lon="-81.400475">
				<ele>11534.318359</ele>
				<time>2016-11-06T14:22:48Z</time>
			</trkpt>
			<trkpt lat="9.392660" lon="-81.399253">
				<ele>11532.311523</ele>
				<time>2016-11-06T14:22:49Z</time>
			</trkpt>
			<trkpt lat="9.391175" lon="-81.398017">
				<ele>11527.229492</ele>
				<time>2016-11-06T14:22:50Z</time>
			</trkpt>
```
```
<trk>
		<trkseg>
			<trkpt lat="-0.756925" lon="-90.315323">
				<ele>17.000000</ele>
				<time>2015-11-07T18:06:20Z</time>
			</trkpt>
			<trkpt lat="-0.756932" lon="-90.315346">
				<ele>17.000000</ele>
				<time>2015-11-07T18:06:24Z</time>
			</trkpt>
```

**Comment by just-Addict** [comment]
If you would please read the post I initially made a loooong time ago...
`I was creating a gpx file using waypoints` 

So, yes, I was adding waypoints manually...

But there's no more need to follow up on this, after all, it was only 9 months ago and I couldn't very well ask my teacher to put things on hold until I got a response so have long since switched to another solution
