### ISSUE TITLE
The time stamp is wrong

### ISSUE THREAD

**Issue by hofty** [merlos/iOS-Open-GPX-Tracker#40]
I left my house at 11:38:50 and when I open the GPX time stamp it shows 19:38:50 so it is 8 hours ahead and therefore my photos do not seem to geotag to the location. Please advise on a possible fix?

**Comment by merlos** [comment]
Hi @hofty,

According to the specification (http://www.topografix.com/gpx_manual.asp#time) GPX time stamps are stored in UTC. The difference means that your time zone is UTC-8. 

As the time in the file follows the specification, I guess there may be an issue on the app you are using for geotagging...
