### ISSUE TITLE
No track data

### ISSUE THREAD

**Issue by midicase** [merlos/iOS-Open-GPX-Tracker#41]
Gave permission to location services.
Started tracking.
Walked around a park for 30 minutes.
Saved.
Sent as email.
Looked in GPX file and there was no tracking data, just a few waypoints I added.

Repeated the above with another park.  Is there something missing?

**Comment by merlos** [comment]
Hi @midicase 

I experienced that a couple of times but I'm not able to reproduce it in a consistent way... Could you please share which device and OS version? Was another application using the GPS?

You know that the device is capturing the track if it is displayed on the map a blue line. When this happens, no line is drawn.

**Comment by midicase** [comment]
Thanks!  iPhone7, iOS 10.3.3.  I just switched after been tracking on android.  
Yes, other apps using the GPS, no line was being drawn even thought my location was moving on the map.  No distance was showing.  I tried a different application, which worked, though I would love to switch back to this open source app.

**Comment by midicase** [comment]
After updating to iOS 11 the problem still exists.  I can reproduce easily by switching to another app that uses the GPS and then back to GPX Tracker.  At this point the application does not track anymore.

**Comment by merlos** [comment]
Thanks midicase.

**Comment by zackad** [comment]
new user here.
installed on iphone 5s with ios 11.4, the app doesn't capture data at all.

**Comment by samuelv0304** [comment]
Here is a process to reproduce the issue:
1. kill all the applications that use the location services
2. disable globally the location services (settings/privacy/location services)
3. start GPX tracker
4. enable the location services (settings/privacy/location services)
5. open GPX tracker
6. start tracking, the message "not getting location" stays displayed, you can define waypoints, but no track is recorded/displayed.

Now, if you runs google maps, kill GPX tracker and relaunch GPX tracker, the track can be recorded and displayed. The message "not getting location" is replaced by coordinates and altitude.

**Comment by bfirsh** [comment]
I reproduced this. iPhone SE, latest iOS, latest version of app. Some clues:

- I was running maps.me routing in background.
- I may have switched very quickly from the app back to maps.me after starting the tracking, so maybe app didn't get a chance to start tracking before getting backgrounded?

Apart from that, I can't think of what might have caused it, and I can't reproduce it. If it happens again I shall try and reproduce the steps.

**Comment by merlos** [comment]
Hi all.

Thank you for sharing your comments. 

I think I was able to fix the issues. In fact, there were more than one. 

First, it seems that a setting of XCode that made a mess.
 https://stackoverflow.com/questions/32543754/ios-9-error-domain-kclerrordomain-code-0-null

In XCode, Menu Product -> Scheme -> Edit Scheme -> Options -> Allow Location Simulation must be unchecked and try providing a default location.

<img width="902" alt="screen shot 2018-09-09 at 09 37 56" src="https://user-images.githubusercontent.com/404446/45265083-38cb6700-b414-11e8-894d-8831ea37b117.png">
(I leave it here for reference)

Additionally, if there was an error or it was denied the access to the location services, it stopped receiving the location. 

Now, the app checks if it has permissions and if does not have, it prompts the user to go to settings.

For now, you can download the source code (master branch) and run it from Xcode, but next app store release will include this fix.
