### ISSUE TITLE
is there a master with swift 4 ?

### ISSUE THREAD

**Issue by EdCafferata** [merlos/iOS-Open-GPX-Tracker#42]

**Comment by merlos** [comment]
Nop, not yet.

**Comment by EdCafferata** [comment]
Hi Merlos,
If if give you a little present could you make the up-to-date version ?
I want to test if i can use it for a Free sailing app :-)
Kind regards, Ed

Verstuurd vanaf mijn iPad

Op 6 mrt. 2018 om 02:21 heeft merlos <notifications@github.com<mailto:notifications@github.com>> het volgende geschreven:


Nop, not yet.

**Comment by merlos** [comment]
Hi @EdCafferata 

The code is still in Swift 3, but now it can be built in the latest version of XCode. External libraries were preventing the app to compile. 

I haven't tried yet to convert it to Swift 4, I have to check if there are many changes... did it take you too much time? 

If you want to help, your help is welcome. Feel free to branch the code and send a pull request. As per now, master branch has the latest commit. 

Thanks, Juan.

**Comment by EdCafferata** [comment]
Hi Merlos, i did make an Swift 4.2 version for you, but git is giving problems.
Can i send it to you per mail ? did start this morning with the last master.

**Comment by merlos** [comment]
Thanks Ed. 

Maybe you were getting the errors because I was also making some commits at the same time, so I am guessing there were some conflicts.
