### ISSUE TITLE
Take advantage of WiFi

### ISSUE THREAD

**Issue by it-werxdotca** [merlos/iOS-Open-GPX-Tracker#47]
More of an enhancement then an issue. 

Allow the app to take advantage of Wifi when it is available.

**Comment by yoiang** [comment]
@it-werxdotca can you explain in more detail about what you mean? 

Do you mean have Wifi assist in accuracy of the GPS? [As far as I know](https://apple.stackexchange.com/a/45510) `CLLocationManager` natively uses Wifi assist methods automagically!

**Comment by merlos** [comment]
I´m closing the issue. Wifi is already being used.  
I have an iPad with no GPS and it is able to position using only Wifi.
