### ISSUE TITLE
Apple Watch App

### ISSUE THREAD

**Issue by merlos** [merlos/iOS-Open-GPX-Tracker#67]
This is a feature request from a user received by another channel: 

> I love your app, and I really appreciate what you’ve built and maintain. 
> 
> If you’re ever interested in exploring Apple Watch app development I would LOVE an Apple Watch accompaniment to your iOS app. Main features I would use:
> - Watch can record tracks and waypoints without connection to phone. 
> - Watch can navigate to saved point without connection to phone by showing an arrow/bearing to the waypoint. 
> 
> With much appreciation and respect,
> Noll

**Comment by vincentneo** [comment]
On a side note, WatchKit apps must use Storyboards for UI. Now that would be slightly inconsistent with the main iOS app. I did a brief test on my fork btw. (unimplemented)

**Comment by merlos** [comment]
@vincentneo, you are right, hehe... but if there is no other option... watch app must use Storyboards and the main app can go on with UI through code.

One thought. Even if it is agreed that creating UI through code was a bad long term decision, still moving everything to storyboards may take some time.

**Comment by vincentneo** [comment]
Did the Apple Watch extension in a fork, using CoreGPX (as I have easily added targets for watchOS).
Pretty rough right now, though testing with the simulator seems to show it working for creation of the GPX file contents. File saving and other features not yet possible.

https://github.com/vincentneo/iOS-Open-GPX-Tracker/tree/GPXKit%2BWatch

**Comment by vincentneo** [comment]
pretty much done! There will not be a map as `WKInterfaceMap` is not quite the same as `MKMapView` , and it has no user interaction capabilities. 

The watch app right now is write only as well, and file name is locked to defaults (date time).

For now, iOS app minimum deployment is increased to iOS 9.3 to support file transfer between watch and phone. I am looking to find a way to counteract with that probably through `@available`.

The signal bars should also be redesigned for the watch UI, which I will attempt when free.

Will do a pull request when ready. 

Lastly, a request: if you have an apple watch, please try it out... I don't have one, and all testing is based on simulator. Real world testing would be great.
