### ISSUE TITLE
Error in distance calculations after loading a map

### ISSUE THREAD

**Issue by merlos** [merlos/iOS-Open-GPX-Tracker#68]
There may be cases in which the distance calculated is not correct
Reference: https://github.com/merlos/iOS-Open-GPX-Tracker/pull/63#issuecomment-454077793

**Comment by huangjimmy** [comment]
Yes, the distance calculation is incorrect.
The distance shown after loading a map is doubled or even quadrupled the real distance.

Something must be wrong!

I have to say that it is not cases but always wrong distance!

**Comment by huangjimmy** [comment]
These are gpx files with duplicate tracks.

[05-Mar-2019-1427.gpx.txt](https://github.com/merlos/iOS-Open-GPX-Tracker/files/2931485/05-Mar-2019-1427.gpx.txt)

[02-Mar-2019.gpx.txt](https://github.com/merlos/iOS-Open-GPX-Tracker/files/2931488/02-Mar-2019.gpx.txt)

**Comment by vincentneo** [comment]
@huangjimmy
I will take a look at these files.

**Comment by vincentneo** [comment]
It appears that the file it self has got two tracks, and the two tracks appear to be the same. Might be a bug in file creation, that I have personally not observed yet. 

The two tracks in the file have the same timestamp as well. Hence this should be a bug regarding file creation, not distance calculation error.

**Comment by huangjimmy** [comment]
I just updated to 1.6 yesterday. 
The previous gpx files are created by previous version.

I am using gpx tracker today and i will see if duplicate tracks occurs again.

**Comment by merlos** [comment]
Fixed since 1.6.0
