### ISSUE TITLE
Display status while sending a file

### ISSUE THREAD

**Issue by merlos** [merlos/iOS-Open-GPX-Tracker#76]
If user is sending a file to the phone, the app is not displaying any visual cue to the user that this action is being performed.

**Comment by merlos** [comment]
This would be the scenario:

The user records a relatively long GPX track on the watch (several MB) and wants to send the file to his iPhone 

Enters the View Files list in the watch selects the file, and among the two options (send to iOS and delete) he chooses to send it to his iPhone. Once he does this action, the watch app directly displays back the list of files, but does not confirm the user without any means that it is sending the files behind the scenes. Because it is a large file, it may take 15 or 20 seconds to get the "File was sent" confirmation.

As solution I can think at least in these two options:
1) Block the UI and display a progress bar and a cancel button. 
2) Display a spinning wheel or even a progress line or background in the cell of the file sent.

For a user that wants to send several files, solution (2) may be better than (1).

**Comment by vincentneo** [comment]
The problem with having a progress indicator is with that watchOS, unlike iOS, doesn't have a native progress bar.
We could have an image-based progress indicator, that cycles through a number of images, acting like a spinning wheel of sorts. Problem is that too less progress imagery would make the spinning wheel choppy. 

Solution 2 seemed like that better choice too.

I'll try it out, probably creating the image sequence for the progress bar, compressing it to as small as possible, and update over here.

**Comment by merlos** [comment]
Some ideas (didn´t check how easy may be the implementation): 

1. An unclosed circle spinning wheel can be created with 1 single image rotated. Does WK support image rotation?
https://getbootstrap.com/docs/4.2/components/spinners/#colors
2. A progress bar may be created by changing the size of a separator or a 1px image rect. 
3. One simple option is to change change the displayed file name name to "Sending..." 
4.  Add an emoticon to the displayed file name  (for instance something like 30-May-2019 1245 ⌚️📲). 

At the end of the day, what is required is to display some visual indicator to tell the user that the request is in progress...

**Comment by vincentneo** [comment]
I am already experimenting with SpriteKit already right now. I'll see how that goes first.

**Comment by vincentneo** [comment]
Having an issue with SpriteKit right now, where nothing loads. Meant to be similar to idea 1.

We can't use rotate images on watchOS, I believe, so any rotation can only be done with a SpriteKit scene. 

We could also have a sequence of images acting as an animation, but could be choppy or space consuming.

Idea 2 could be tried too, while Idea 3 & 4 seems a kinda unpolished, so I'm hoping to not use those ideas.

I will play around with SpriteKit some more, hoping to be able to use it, as its quite a lot nice, I believe.
