### ISSUE TITLE
Refactor Apple Watch send file indicator

### ISSUE THREAD

**Issue by merlos** [merlos/iOS-Open-GPX-Tracker#88]
As discussed in #83 
In send `Progress Group` should be encapsulated in a class, so it de-clutters the ViewController. Also, it can be the foundation to provide async feedback in other scenarios in the future.

**Comment by vincentneo** [comment]
One thing about WatchKit, is that classes like `WKInterfaceGroup` or `WKInterfaceImage` should not be subclassed, or basically any class that is subclassed from `WKInterfaceObject`

> Do not subclass or create instances of this class yourself. // from [`WKInterfaceGroup`](https://developer.apple.com/documentation/watchkit/wkinterfacegroup)'s docs

> Do not subclass or create instances of this class, or any of its subclasses, yourself. Instead, define outlets in your interface controller class and connect them to the corresponding objects in your storyboard file. // from [`WKInterfaceObject`](https://developer.apple.com/documentation/watchkit/wkinterfaceobject)'s docs

**Comment by merlos** [comment]
You´re right. Closed.
