### ISSUE TITLE
Transferred WatchOS files won't be shown immediately

### ISSUE THREAD

**Issue by mig8447** [merlos/iOS-Open-GPX-Tracker#91]
When iOS app is in file view, file transfer from WatchOS will notify it succeeded but the file will not be shown in the file browser until you close it and open it again

**Comment by vincentneo** [comment]
I have previously seen the issue as well, as seen in https://github.com/merlos/iOS-Open-GPX-Tracker/issues/78#issuecomment-471555681

Should be fixable, by updating the table when a file is received.
