### ISSUE TITLE
Is Offline Navigation possible ?

### ISSUE THREAD

**Issue by F3000** [merlos/iOS-Open-GPX-Tracker#92]
is it possible to load a .gpx file and start the navigation with that file ?

**Comment by vincentneo** [comment]
Yes it is possible, but if you need the map interface, you should use third party map (like OpenStreetMap, etc) options that can be cached. They can be found in the settings of the app. The GPS tracking functionality should still function in offline situations too, except for in airplane mode.

**Comment by F3000** [comment]
Thanks for the info . I want to do following with your app: 

Create a .gpx Route etc... in google maps . Import it in your App and Cache the map. After that navigate along the route . 

Is that possible ?
