### ISSUE TITLE
Navigate on AppleWatch 

### ISSUE THREAD

**Issue by F3000** [merlos/iOS-Open-GPX-Tracker#94]
There should be an option to see arrows/warnings on the watch when navigation is on.
The function should use haptic feedback. 

Use case : I don’t have to look at the phone . I see the arrows on the map and have haptic feedback

**Comment by vincentneo** [comment]
The Apple Watch does not contain the necessary hardware that makes the 'compass' works. Basically, the latitude, longitude and elevation is retrievable, but not the heading direction, as the required hardware is not available.

Read [this](https://stackoverflow.com/questions/27420439/using-core-location-in-apple-watchkit) if you want to learn more about it.

**Comment by F3000** [comment]
Ok this is clear . But the watch can show navigation arrows etc... like with the own Apple maps app .

**Comment by vincentneo** [comment]
Hmm. Navigation Arrows? Sorry I don't have an apple watch, despite doing most of the work of the watch app (I'm just a collaborator, in case you haven't noticed.)

So I don't know much about the native apps of the apple watch. Regardless, this project is currently more of just a 'GPX tracker' as the name suggests.

**Comment by F3000** [comment]
Here are some examples : 
Maybe this helps .. . 

![A335450A-9B55-41ED-962D-4187E59B37DD](https://user-images.githubusercontent.com/8161283/56837164-ba73e600-6879-11e9-8130-6c48c1b61bfd.jpeg)
![1C6EA633-626B-4589-BF7B-E9DA4AFEADE6](https://user-images.githubusercontent.com/8161283/56837167-ba73e600-6879-11e9-8422-51d6e309edcd.jpeg)


You are the only collaborator ?
