### ISSUE TITLE
Show lines between markers on the map 

### ISSUE THREAD

**Issue by F3000** [merlos/iOS-Open-GPX-Tracker#95]
Is there a seething for that ?

When not , there should be a setting to connect markers (over streets) .

**Comment by vincentneo** [comment]
I don't quite get that. Can you elaborate about this?

**Comment by F3000** [comment]
Sorry i mean a possible route between markers . 
At the moment two markers are not connected by each other.

**Comment by vincentneo** [comment]
Markers as in? The 'pins' / waypoints? 
Technically, the gpx file format allows for a `route` as well, or is that what you wish, will be represented in the map?

**Comment by F3000** [comment]
Ok than is Pin the right wird . 

Look at the picture : I have drawed a red line where a possible connector could be 

![6008261A-84F6-4375-B9F6-543FE2CAFA25](https://user-images.githubusercontent.com/8161283/56816262-7534c180-6843-11e9-9f61-0a3fe9363e02.jpeg)

**Comment by F3000** [comment]
Sorry not closed

**Comment by vincentneo** [comment]
Alright, I think I get it. Should be implemented as a route technically if you wanted this, and that a new button should be added, for this kind of functionality, to not impact the current 'waypoint' functionality.
(As a Waypoint should not be represented in such a way, as a waypoint describes a point created at the map to represent a place of certain significance, some thing like that)

**Comment by F3000** [comment]
Sorry but now it’s ok

**Comment by merlos** [comment]
What you are proposing looks like the generation of routes, some kind of GPX editor... 

Open GPX tracker, as its names says is a tracker, its primary goal is to track your current location and where you have been.  

Although interesting, I think it is a bit out of the scope in the short term.
